version: '3'
services:
  app:
    build:.
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://username:password@db:5432/dbname
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname