FROM postgres:13

ENV POSTGRES_USER=username
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=dbname

COPY init.sql /docker-entrypoint-initdb.d/FROM postgres:13

ENV POSTGRES_USER=username
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=dbname

COPY init.sql /docker-entrypoint-initdb.d/